Blumengasse_IoT/Blumengasse_IoT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('PlantSensors.urls')),
]

Blumengasse_IoT/PlantSensors/urls.py
from django.urls import path

from . import views

app_name = "PlantSensors"
urlpatterns = [
    path('', views.index, name='index'),
    path('datum', views.date_view, name='date_view'),
    path('data/<int:sensor_id>', views.get_data, name="get_data"),
    path('register', views.register_sensor, name="register_sensor")
]

Blumengasse_IoT/PlantSensors/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Sensor(models.Model):
    sensor_id = models.IntegerField(unique=True)
    sensor_name = models.CharField(max_length=20, unique=True)
    sensor_type = models.CharField(max_length=20)
    sensor_interval = models.IntegerField()

    def __str__(self):
        return str(self.sensor_name)

class measurement(models.Model):
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE)
    reading = models.FloatField()
    type = models.CharField(max_length=20)
    time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.sensor.sensor_name + self.type + str(self.reading)

Blumengasse_IoT/PlantSensors/forms.py
from django import forms
import datetime

coarse_CHOICES = (('1', '1'), ('10', '10'), ('20', '20'), ('100', '100'), ('1000', '1000'))
time_CHOICES = (('1', '1h'), ('24', '24h'), ('168', '1 Woche'), ('720', '1 Monat'), ('0', 'Gesamter Zeitraum'))

class coarse(forms.Form):
    Auflösung = forms.TypedChoiceField(choices=coarse_CHOICES, coerce=int)
    Zeitrahmen = forms.TypedChoiceField(choices=time_CHOICES, coerce=int)

class datepicker(forms.Form):
    Anfang = forms.DateField(initial=datetime.date.today, widget=forms.SelectDateWidget())
    Ende = forms.DateField(initial=datetime.date.today, widget=forms.SelectDateWidget())
    Auflösung = forms.TypedChoiceField(choices=coarse_CHOICES, coerce=int)

Blumengasse_IoT/PlantSensors/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseForbidden, JsonResponse
import datetime
import json
from django.views.decorators.csrf import csrf_exempt
from datetime import datetime, timedelta

from .models import Sensor, measurement

from plotly.offline import plot
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from .forms import coarse, datepicker

def index(request, coarsing=1, timeframe=24):
    if 'Auflösung' in request.GET.keys():
        coarsing=int(request.GET['Auflösung'])
    if 'Zeitrahmen' in request.GET.keys():
        timeframe=int(request.GET['Zeitrahmen'])

    plots = []

    for s in Sensor.objects.all():
        queryset = measurement.objects.filter(sensor=s)

        # Timeframe filter
        if timeframe!=0:
            now = datetime.now()
            earlier = now - timedelta(hours=timeframe)
            queryset = queryset.filter(time__range=[earlier, now])

        types = list(queryset.order_by().values_list('type', flat=True).distinct())
        for type in types:
            q = queryset.filter(type=type)

            time = []
            data = []

            for r in q:
                time.append(r.time.isoformat())
                data.append(r.reading)
            time = time[::coarsing]
            data = data[::coarsing]
            #plots.append({'time': time, 'data': data, 'type': s.sensor_type})
            plots.append((time,data,type,s.sensor_name))


    context = {'plots': plots}
    context['form'] = coarse(initial={'Auflösung':str(coarsing), 'Zeitrahmen':str(timeframe)})


    return render(request, 'PlantSensors/charts.html', context=context)

def date_view(request, coarsing=20):
    begin = datetime.now()- timedelta(hours=24)
    end = datetime.now()
    if 'Auflösung' in request.GET.keys():
        coarsing=int(request.GET['Auflösung'])
    if 'Anfang_month' in request.GET.keys():
        begin=datetime(year=int(request.GET['Anfang_year']), month=int(request.GET['Anfang_month']), day=int(request.GET['Anfang_day']))
    if 'Ende_month' in request.GET.keys():
        end=datetime(year=int(request.GET['Ende_year']), month=int(request.GET['Ende_month']), day=int(request.GET['Ende_day']))


    plots = []

    for s in Sensor.objects.all():
        queryset = measurement.objects.filter(sensor=s)

        queryset = queryset.filter(time__range=[begin, end])

        types = list(queryset.order_by().values_list('type', flat=True).distinct())
        for type in types:
            q = queryset.filter(type=type)
            time = []
            data = []

            for r in q:
                time.append(r.time.isoformat())
                data.append(r.reading)
            time = time[::coarsing]
            data = data[::coarsing]
            #plots.append({'time': time, 'data': data, 'type': s.sensor_type})
            plots.append((time,data,type,s.sensor_name))


    context = {'plots': plots}
    context['form'] = datepicker(initial={'Anfang':begin, 'Ende':end})


    return render(request, 'PlantSensors/charts.html', context=context)


@csrf_exempt
def get_data(request, sensor_id):
    if not request.method=='POST':
        return HttpResponseForbidden('Nothing to get here')
    if not request.headers['token'] == '1234':
        return HttpResponseForbidden('Permission denied')

    data = json.loads(request.body)
    sensor = Sensor.objects.get(sensor_id=sensor_id)
    for key, value in data.items():
        print(value)
        new_measurement = measurement(sensor=sensor, reading=value, type=key)
        new_measurement.save()
    settings = {'interval': sensor.sensor_interval}
    return JsonResponse(settings)

@csrf_exempt
def register_sensor(request):
    data = json.loads(request.body)
    if not request.method=='POST':
        return HttpResponseForbidden('Nothing to get here')
    if not request.headers['token'] == '1234':
        return HttpResponseForbidden('Permission denied')
    if not Sensor.objects.filter(sensor_id=data['sensor_id']):
        s = Sensor(sensor_id=data['sensor_id'], sensor_type=data['sensor_type'], sensor_name=data['sensor_id'], sensor_interval=data['interval'])
        s.save()
        return HttpResponse("Gotcha")
    return HttpResponse("Already know you")

Blumengasse_IoT/PlantSensors/templates/PlantSensors/charts.html
<!DOCTYPE HTML>
{% extends "base.html" %}
{% load static %}

{% block body %}
  <div class="row min-vh-100 align-items-center p-md-5 present">
    <!--      <div id="plotting"></div>     -->
    <form method = "GET">
        {{ form }}
        <input type = "submit" value = "Submit">
    </form>
    {% for plot in  plots%}
      <div class="col-md-6 p-2 bd-highlight">
        <canvas id="{{plot.3}}-{{plot.2}}"></canvas>
      </div>
    {% endfor %}
  </div>
{% endblock %}


{% block javascript %}

<script>
{% for plot in  plots%}
  var plot_canvas = document.getElementById('{{plot.3}}-{{plot.2}}');
  var myChart = new Chart(plot_canvas, {
      type: 'line',
      data: {
          labels: {{plot.0|safe}},
          datasets: [{
              label: '{{plot.2}}',
              data: {{plot.1}},
              borderColor: [
                  'rgba(255, 99, 132, 1)',
              ],
              borderWidth: 1,
              pointRadius: 0.1,
              pointHoverRadius: 4,
              tension: .1,
          }]
      },
      options: {
          plugins: {
              title: {
                  display: true,
                  text: '{{plot.3}}'
              },
          },
          scales: {
              x: {
                  type: 'time',
                  time: {
                      // unit: 'minute',
                      minUnit: 'minute'
                  },
                  ticks: {
                      autoSkip: true,
                      maxTicksLimit: 15
                  },
              }
          },
          // responsive: true,
          // maintainAspectRatio: false
      }
  });
{% endfor %}

</script>

{% endblock %}

Blumengasse_IoT/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <title>{% block title%}{% endblock %}</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'scss/main.css' %}"/>
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/bootstrap-icons/font/bootstrap-icons.css' %}">
    <style>
        {% block style %}
        {% endblock style %}
        @media only screen and (max-width: 700px) {
          i {
            font-size: x-large;
          }
        }
    </style>
  </head>
  <body>

  <div class="container-fluid">
        <div class="row">
            <div class="col-md-auto fixed bg-dark ">
                <div class="d-flex flex-md-column flex-row flex-nowrap bg-light align-items-center sticky-top bg-dark">
                    <a href="/" class="d-block p-1 link-dark text-decoration-none" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Icon-only">
                        <i class="bi-bootstrap fa-1"></i>
                    </a>
                    <ul class="nav nav-pills nav-flush flex-md-column flex-row flex-nowrap mb-auto mx-auto text-center align-items-center">
                        <li class="nav-item">
                            <a href="{% url 'PlantSensors:index' %}" class="nav-link py-3 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Home">
                                <i class="bi-house fa-1 p-4 p-md-0"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'PlantSensors:date_view' %}" class="nav-link link-primary py-3 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Dashboard">
                                <i class="bi bi-calendar fa-1 p-4 p-md-0"></i>
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'admin:index' %}" class="nav-link py-3 px-1" title="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-original-title="Dashboard">
                                <i class="bi-gear fa-1 p-4 p-md-0"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md p-3 min-vh-100">
              <!--                content               -->
              {% block body %}
              {% endblock body %}

            </div>
        </div>
    </div>



    <script src="{% static 'myScript.js' %}"></script>
    <script src="{% static 'node_modules/chart.js/dist/chart.js' %}"></script>
    <script src="{% static 'bootstrap-5.1.1-dist/js/bootstrap.min.js' %}"></script>

    <!-- Maybe download this -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js/dist/chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>

    {% block javascript %}
    {% endblock javascript %}
  </body>
</html>